extends: 'airbnb-base'

env:
  node: true
  jest: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  import/extensions:
    - error
    - never
    - js: always
  no-underscore-dangle: ["error", { "allow": ["__dirname", "__filename"] }]